apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: twitter-stream
  labels:
    name: twitter-stream
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: twitter-stream
    spec:
      containers:
      - name: twitter-to-pubsub
        image: gcr.io/$PROJECT_ID/pubsub_pipeline
        env:
        - name: PROCESSINGSCRIPT
          value: twitter-to-pubsub
        # Change this to your pubsub topic
        - name: PUBSUB_TOPIC
          value: projects/$PROJECT_ID/topics/new_tweets
        # Change the following four settings to your twitter credentials
        # information.
        - name: CONSUMERKEY
          value: $CONSUMERKEY
        - name: CONSUMERSECRET
          value: $CONSUMERSECRET
        - name: ACCESSTOKEN
          value: $ACCESSTOKEN
        - name: ACCESSTOKENSEC
          value: $ACCESSTOKENSEC
        - name: TWSTREAMMODE
          value: filter
